AI HomeWork 

In [119]:
import numpy as np
import jdc #manupular class  https://alexhagen.github.io/jdc/
import random
import matplotlib.pyplot as plt

EXERCICIO FIXACÃO
ALUNO: MANOEL WAGNER GAIA DE MELO

In [120]:
#Criar Matrix para o 
mapRobot = np.zeros((10,10))
mapRobot[9,9]=-999
mapRobot[0,0]=1
print(mapRobot)

mapRobot.shape
mapRobot.ndim


[[   1.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0. -999.]]


2

In [121]:
#Criamos uma matrix com as posições de cada Casa de 0 a 99

mapPosition = mapRobot
y=0
X=0
count=0
for y in range(10):
    for x in range(10):
        
        mapPosition[y,x]=count
        count+=1

mapPosition


array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [122]:

stateFuture = 0
move = 0 

#Função para verificar que o Agente não ultrapassa o limites do capo
def checkWall(move,state,stateFuture):
    #Zerando as variaveis


    print("==Iniciar a Função== CheckWall")
    print("State Initial", state)
    #print("Variaveis vazias:",yFuture, xFuture)
    #Dividimos o numero em Decimais e Inteiros
    yFuture, xFuture = divmod(stateFuture,10)
    print("Variaveis Separadas:",yFuture, xFuture)

    if (move==0 or move==1) : #up // down
        #print("move1: UP -", move)
        #Teste que esta no limite das paredes cima e baixo
        if (yFuture >= 0 and yFuture <= 9) and (xFuture >= 0 and xFuture <= 9) :
            state = stateFuture
            return state
        else:
            return state
    print("State Final", state)

    if (move==2 or move==3) : #left // right
        #Teste que esta no limite das paredes
        #print("move2:", move)
        if (yFuture >= 0 and yFuture <= 9) and (xFuture >= 0 and xFuture <= 9)  :
            state= stateFuture
            return state
        else:
            return state
    
    print("==Final a Função== CheckWall -State Final:", state)
state = checkWall(move,state,stateFuture)


==Iniciar a Função== CheckWall
State Initial 0
Variaveis Separadas: 0 0


In [123]:
'''
ActionRobot => Função para movimentar o Robô, são 4 movimentos, (up,down, left,right)
'''
#state =0
def actionRobot(state):
    print("==Iniciar a Função== actionRobot")
    yFuture = 0
    xFuture = 0
      
    yNow, xNow = divmod(state,10)
    
    action= random.randint(0,3) 
    action=2
    if action ==0 : 
        acao = "up"
        yFuture = yNow - 1  
    elif action ==1 :
        acao = "down" 
        yFuture = yNow + 1
    elif action ==2 :
        acao = "left" 
        xFuture = xNow - 1
    elif action ==3 :
        acao = "right" 
        xFuture = xNow + 1
    print ("state = ", state)
    print ("Action = ",acao, action)
    print ("Yfuture = ", yFuture)
    print ("xfuture = ", xFuture)
    
    stFuture = (yFuture *10) + xFuture
    print ("stateFuture = ", stFuture)
    stFuture = checkWall(action,state,stFuture)
    
    
    
    print("== Final a Função == actionRobot: ", acao,"-", action , " nextState:", stFuture  )
    return stFuture 

state = 0
state = actionRobot(state)
 

==Iniciar a Função== actionRobot
state =  0
Action =  left 2
Yfuture =  0
xfuture =  -1
stateFuture =  -1
==Iniciar a Função== CheckWall
State Initial 0
Variaveis Separadas: -1 9
State Final 0
== Final a Função == actionRobot:  left - 2  nextState: 0


In [124]:

#state = 0

#Função de Reward
def CheckReward(state, Reward=0):
    
    print("==Iniciar a Função== CheckReward - Reward:", Reward,"StateReward", state)
    if state == 99 :
        Reward = Reward + 100
        state = 0
    else: 
        Reward = Reward 
    
    return (state)
    print("==Final Função== CheckReward: ", Reward)
            
state = CheckReward(state)
print(state,Reward)

==Iniciar a Função== CheckReward - Reward: 0 StateReward 0
0 0


In [ ]:
i = 1
Reward = 0

for i in range(100):
    #Verifica a proxima

IndentationError: unexpected indent (<ipython-input-125-fa7e4374b663>, line 10)